name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: "${{ vars.VERSION_TAG }}.${{ github.run_number }}"
      IMAGE_NAME: "robkaandorp/drone-portainer"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ vars.VERSION_TAG }}
          ${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          ${{ env.IMAGE_NAME }}:latest
